// File generated by FlutterFire CLI and cleaned for Web.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web; // Forzamos a que devuelva siempre la configuración Web
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFQ0mhDNFaMnljm9xh06WYFhP_UUn-XE',
    appId: '1:889037144626:web:01efd65bb97982dd5af22b',
    messagingSenderId: '889037144626',
    projectId: 'petwatch-sm',
    authDomain: 'petwatch-sm.firebaseapp.com',
    storageBucket: 'petwatch-sm.firebasestorage.app',
    measurementId: 'G-708Y9WE6QH',
  );
}